# This is a basic workflow to help you get started with Actions

name: Get data from private repo
on:
  schedule:
    - cron: '30 5 * * *' # everyday at 05:30 UTC

jobs:
  # load job
  load_data:
    runs-on: ubuntu-latest

    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Copy file from url
    - name: Copy file
      run: |
        curl -o Bildung_TrainingMathematik.csv https://raw.githubusercontent.com/bildungsmonitoringZH/covid19_edu_lmvzmath/master/Bildung_TrainingMathematik.csv?token=AJUPNJZGIFCCY3AD6SGQ7BC65MW7M
        if egrep -q '^[0-9]{3}\:' Bildung_TrainingMathematik.csv; then exit 1; fi

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update Bildung_TrainingMathematik.csv
        branch: ${{ github.head_ref }}
